apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pythonapp
  template: 
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
#        image: "{{ .Values.image.repo}}/{{ .Values.image.name}}:{{ .Chart.AppVersion }}"
        image: "alezander/python_app:1.10.2"
        ports:
          - name: http-port
            containerPort: 5000