apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: {{ if eq .Release.Namespace "ot-onboarding-dev" }} {{ .Values.replicas.dev }}
            {{ else if eq .Release.Namespace "ot-onboarding-prod" }} {{ .Values.replicas.prod }}  {{ end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pythonapp
  template: 
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: "{{ .Values.image.repo}}/{{ .Values.image.name}}:{{ .Chart.AppVersion }}"
        ports:
          - name: http-port
            containerPort: 5000